--CREATE DATABASE ProjectDbTest

USE ProjectDbTest

CREATE TABLE Users (
	Id INT PRIMARY KEY NOT NULL,
	Username NVARCHAR(100) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(MAX) NOT NULL,
	Email NVARCHAR(256) NOT NULL
)

CREATE TABLE Categories (
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	CreatedOn DATETIME2 NOT NULL,
	ModifiedOn	 DATETIME2 NOT NULL
)

CREATE TABLE Countries (
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	CreatedOn DATETIME2 NOT NULL,
	ModifiedOn	 DATETIME2 NOT NULL
)

CREATE TABLE Places (
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(300) NOT NULL,
	[Description] NVARCHAR(1500) NOT NULL,
	CountryId INT NOT NULL FOREIGN KEY (CountryId) REFERENCES Countries(Id),
	CategoryId INT NOT NULL FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
	UserId INT NOT NULL FOREIGN KEY (UserId) REFERENCES Users(Id),
	CreatedOn DATETIME2 NOT NULL,
	ModifiedOn	 DATETIME2 NOT NULL,
	IsDeleted BIT NOT NULL,
	DeletedOn DATETIME2 NULL
)

CREATE TABLE FavoritePlaces (
	PlaceId INT NOT NULL,
	UserId INT NOT NULL,
	PRIMARY KEY (PlaceId, UserId),
	FOREIGN KEY (PlaceId) REFERENCES Places(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
)

CREATE TABLE PlacePhotos (
	Id INT PRIMARY KEY NOT NULL,
	[Url] NVARCHAR(Max) NOT NULL,
	PlaceId INT NOT NULL FOREIGN KEY(PlaceId) REFERENCES Places(Id),
	CreatedOn DATETIME2 NOT NULL,
	ModifiedOn	 DATETIME2 NOT NULL,
	IsDeleted BIT NOT NULL,
	DeletedOn DATETIME2 NULL
)

CREATE TABLE Reviews (
	Id INT PRIMARY KEY NOT NULL,
	Content NVARCHAR(500) NOT NULL,
	Likes INT NOT NULL DEFAULT 0,
	Rating INT NOT NULL,
	PlaceId INT NOT NULL FOREIGN KEY(PlaceId) REFERENCES Places(Id),
	UserId INT NOT NULL FOREIGN KEY (UserId) REFERENCES Users(Id),
	CreatedOn DATETIME2 NOT NULL,
	ModifiedOn	 DATETIME2 NOT NULL,
	CONSTRAINT CHK_Rating CHECK (Rating>=1 AND Rating<=5),
)